# Generated by Django 3.1.7 on 2021-04-04 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210404_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogger_detail',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='blogger_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=123),
            preserve_default=False,
        ),
    ]
