# Generated by Django 3.2 on 2021-04-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210417_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='types',
        ),
    ]
