# Generated by Django 3.2 on 2021-05-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_type_product_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images1',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='images2',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
